[GENERAL]
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"
KEEP_ALIVE = "5m" # How long to keep Ollama models loaded into memory. (Instead of using -1 use "-1m")

[MODELS.OPENAI]
API_KEY = "${OPENAI_API_KEY}"

[MODELS.GROQ]
API_KEY = "${GROQ_API_KEY}"

[MODELS.ANTHROPIC]
API_KEY = "${ANTHROPIC_API_KEY}"

[MODELS.GEMINI]
API_KEY = "${GEMINI_API_KEY}"

[MODELS.CUSTOM_OPENAI]
API_KEY = "${CUSTOM_OPENAI_API_KEY}"
API_URL = "${CUSTOM_OPENAI_API_URL}"
MODEL_NAME = "${CUSTOM_OPENAI_MODEL_NAME}"

[MODELS.OLLAMA]
API_URL = "${OLLAMA_API_URL}" # Ollama API URL - http://host.docker.internal:11434

[MODELS.DEEPSEEK]
API_KEY = "${DEEPSEEK_API_KEY}"

[MODELS.AIMLAPI]
API_KEY = "${AIMLAPI_API_KEY}" # Required to use AI/ML API chat and embedding models

[MODELS.LM_STUDIO]
API_URL = "${LM_STUDIO_API_URL}" # LM Studio API URL - http://host.docker.internal:1234

[API_ENDPOINTS]
SEARXNG = "${SEARXNG_API_URL}" # SearxNG API URL - http://localhost:32768
