version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-https://searxng.coolify.infoboi.site}
    ports:
      - "32768:8080"
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=${SEARXNG_API_URL:-http://searxng:8080}
    depends_on:
      - searxng
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - AIMLAPI_API_KEY=${AIMLAPI_API_KEY}
      - OLLAMA_API_URL=${OLLAMA_API_URL}
      - CUSTOM_OPENAI_API_KEY=${CUSTOM_OPENAI_API_KEY}
      - CUSTOM_OPENAI_API_URL=${CUSTOM_OPENAI_API_URL}
      - CUSTOM_OPENAI_MODEL_NAME=${CUSTOM_OPENAI_MODEL_NAME}
      - LM_STUDIO_API_URL=${LM_STUDIO_API_URL}
      - SEARXNG_API_URL=${SEARXNG_API_URL:-http://searxng:8080}
    ports:
      - "3001:3001"
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:3001}
    depends_on:
      - perplexica-backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:3001}
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:
    driver: bridge

